version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAScafolding608Project
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAScafolding608Project
  gitUsername: siqagituser
  gitBranch: main
